const employeeData = [
  {
    name: "Vijay Malya",
    position: "Bank Manager",
    email: "employee@gmail.com",
    about: "I am a very good manager , lorem ipsum door.",
  },
  {
    name: "Anil",
    position: "Engineer",
    email: "employee@gmail.com",
    about: "I am a very good engineer , lorem ipsum door.",
  },
  {
    name: "Suresh",
    position: "Developer",
    email: "employee@gmail.com",
    about: "I am a very good engineer , lorem ipsum door.",
  },
  {
    name: "Amar",
    position: "Scientist",
    email: "employee@gmail.com",
    about: "I am a very good engineer , lorem ipsum door.",
  },
  {
    name: "Siddhu Singh",
    position: "Manager",
    email: "employee@gmail.com",
    about: "I am a very good manager , lorem ipsum door.",
  },
  {
    name: "Amar",
    position: "Scientist",
    email: "employee@gmail.com",
    about: "I am a very good engineer , lorem ipsum door.",
  },
  {
    name: "Siddhu Singh",
    position: "Manager",
    email: "employee@gmail.com",
    about: "I am a very good manager , lorem ipsum door.",
  },
  {
    name: "Amar",
    position: "Scientist",
    email: "employee@gmail.com",
    about: "I am a very good engineer , lorem ipsum door.",
  },
  {
    name: "Siddhu Singh",
    position: "Manager",
    email: "employee@gmail.com",
    about: "I am a very good manager , lorem ipsum door.",
  },
  {
    name: "Amar",
    position: "Scientist",
    email: "employee@gmail.com",
    about: "I am a very good engineer , lorem ipsum door.",
  },
  {
    name: "Siddhu Singh",
    position: "Manager",
    email: "employee@gmail.com",
    about: "I am a very good manager , lorem ipsum door.",
  },
  {
    name: "Amar",
    position: "Scientist",
    email: "employee@gmail.com",
    about: "I am a very good engineer , lorem ipsum door.",
  },
  {
    name: "Siddhu Singh",
    position: "Manager",
    email: "employee@gmail.com",
    about: "I am a very good manager , lorem ipsum door.",
  },
  {
    name: "Amar",
    position: "Scientist",
    email: "employee@gmail.com",
    about: "I am a very good engineer , lorem ipsum door.",
  },
  {
    name: "Siddhu Singh",
    position: "Manager",
    email: "employee@gmail.com",
    about: "I am a very good manager , lorem ipsum door.",
  },
  {
    name: "Amar",
    position: "Scientist",
    email: "employee@gmail.com",
    about: "I am a very good engineer , lorem ipsum door.",
  },
  {
    name: "Siddhu Singh",
    position: "Manager",
    email: "employee@gmail.com",
    about: "I am a very good manager , lorem ipsum door.",
  },
  {
    name: "Amar",
    position: "Scientist",
    email: "employee@gmail.com",
    about: "I am a very good engineer , lorem ipsum door.",
  },
  {
    name: "Siddhu Singh",
    position: "Manager",
    email: "employee@gmail.com",
    about: "I am a very good manager , lorem ipsum door.",
  },
  {
    name: "Amar",
    position: "Scientist",
    email: "employee@gmail.com",
    about: "I am a very good engineer , lorem ipsum door.",
  },
  {
    name: "Siddhu Singh",
    position: "Manager",
    email: "employee@gmail.com",
    about: "I am a very good manager , lorem ipsum door.",
  },
  {
    name: "Amar",
    position: "Scientist",
    email: "employee@gmail.com",
    about: "I am a very good engineer , lorem ipsum door.",
  },
  {
    name: "Siddhu Singh",
    position: "Manager",
    email: "employee@gmail.com",
    about: "I am a very good manager , lorem ipsum door.",
  },
  {
    name: "Amar",
    position: "Scientist",
    email: "employee@gmail.com",
    about: "I am a very good engineer , lorem ipsum door.",
  },
  {
    name: "Siddhu Singh",
    position: "Manager",
    email: "employee@gmail.com",
    about: "I am a very good manager , lorem ipsum door.",
  },
  {
    name: "Amar",
    position: "Scientist",
    email: "employee@gmail.com",
    about: "I am a very good engineer , lorem ipsum door.",
  },
  {
    name: "Siddhu Singh",
    position: "Manager",
    email: "employee@gmail.com",
    about: "I am a very good manager , lorem ipsum door.",
  },
  {
    name: "Amar",
    position: "Scientist",
    email: "employee@gmail.com",
    about: "I am a very good engineer , lorem ipsum door.",
  },
  {
    name: "Siddhu Singh",
    position: "Manager",
    email: "employee@gmail.com",
    about: "I am a very good manager , lorem ipsum door.",
  },
  {
    name: "Amar",
    position: "Scientist",
    email: "employee@gmail.com",
    about: "I am a very good engineer , lorem ipsum door.",
  },
  {
    name: "Siddhu Singh",
    position: "Manager",
    email: "employee@gmail.com",
    about: "I am a very good manager , lorem ipsum door.",
  },
  {
    name: "Arijit Singh",
    position: "Singer",
    email: "employee@gmail.com",
    about: "I am a very good singer , lorem ipsum door.",
  },
  {
    name: "Vijay Malya",
    position: "Bank Manager",
    email: "employee@gmail.com",
    about: "I am a very good manager , lorem ipsum door.",
  },
  {
    name: "Anil",
    position: "Engineer",
    email: "employee@gmail.com",
    about: "I am a very good engineer , lorem ipsum door.",
  },
];
export { employeeData };
